collatz recursion
hannako/CS50 pull request #4
Opened 2017-01-15 11:04 UTC by hannako

As I mentioned on my email, this was just a little problem set in one of the 'shorts'.

2017-01-16 14:34 UTC, hcarver requested changes

2017-01-16 14:34 UTC, hcarver commented on p_sets/4/collatz.rb
> +    int.even? ? steps(int / 2, count) : steps((3 * int + 1), count)
Personally, I prefer ruby's
```
if
else
end
``` 
syntax to the ternary operator (`? :`) - I think it's more legible. Not sure what our style guide has to say on that though.

2017-01-23 18:11 UTC, hannako commented
@hcarver Is it OK to merge this?

2017-01-23 18:49 UTC, hcarver approved these changes
Yep, fine to merge 👍

2017-01-27 10:41 UTC, merged